import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "../components/Header";
import Footer from "../components/Footer";
import brand from "../public/brand.png";
import download from "../public/download.svg";

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <div className="flex justify-between items-start w-11/12">
          <Image src={brand} alt="brand" width={350} height={200} />
          <div className="flex flex-col space-y-8 w-3/5">
            <div className="text-sm flex flex-col space-y-2">
              <div className="flex flex-row">
                <div className="border-t-2 border-blue w-8 h-1 my-auto mx-2"></div>
                <p className="text-blue font-bold">Get to Know Us</p>
              </div>
              <p className="font-normal">
              As a highly diversified group, our primary objective is to satisfy our client's needs. Our success in achieving this is measured by our client's perception of the seamless execution and achieving the highest level of readiness, communication, quality and safety to our clients. 
              </p>
              <p className="font-bold ">
              We deal in: 
              </p>
              <ul>
                <li>Logistics</li>
                <li>Mining</li>
                <li>Supply of Construction Material </li>
                <li>Real Estate </li>
                <li>Software Agency</li>
              </ul>
            </div>
            <button className="bg-blue text-white font-bold text-lg rounded-full w-64 h-12 flex justify-evenly items-center cursor-pointer">
              <Image src={download} alt="download" />
              Download Our Profile
            </button>
          </div>
        </div>
      </main>
      <div className="flex justify-center h-24 items-center z-10">
          <Link href="/">
        <button className=" text-blue flex justify-evenly w-32 cursor-pointer">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className=" h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M10 19l-7-7m0 0l7-7m-7 7h18"
            />
          </svg>
          Go Back
        </button>
        </Link>
      </div>

     <Footer/>
    </div>
  );
};

export default About;
