import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Header from "../components/Header";
import Footer from "../components/Footer"
import brand from "../public/brand.png";

const Contact: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <div className="flex justify-between items-start w-11/12">
          <Image src={brand} alt="brand" width={350} height={200} />
          <div className="flex flex-col space-y-8 w-3/5">
            <div className="flex flex-row">
              <div className="border-t-2 border-blue w-8 h-1 my-auto mx-2"></div>
              <p className="text-blue text-sm">Get in Touch</p>
            </div>
            <div className="flex flex-col ml-12">
              <p>We would like to hear from you...</p>
              <input
                className="border-b border-gray p-2 mb-2 w-3/4 outline-none"
                placeholder="Your Name"
                type="text"
              />
              <input
                className="border-b border-gray p-2 mb-2 w-3/4 outline-none"
                placeholder="Your Email"
                type="email"
              />
              <input
                className="border-b border-gray p-2 mb-2 w-3/4 outline-none"
                placeholder="Your Message"
                type="text"
              />
            </div>
            <div className="flex justify-center items-center">
              <button onClick={() => console.log("Sent")} className="bg-blue text-white w-36 h-12 flex justify-center items-center rounded-full">
                Submit
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M14 5l7 7m0 0l-7 7m7-7H3"
                  />
                </svg>
              </button>
            </div>
          </div>
        </div>
      <div className="flex justify-center items-center cursor-pointer">
          <Link href="/about">
        <button onClick={() => console.log("Clicked")} className=" text-blue flex justify-evenly w-32 h-12 items-center cursor-pointer">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className=" h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M10 19l-7-7m0 0l7-7m-7 7h18"
            />
          </svg>
          Go Back
        </button>
        </Link>
      </div>
      </main>
<Footer/>
    </div>
  );
};

export default Contact;
