import type { NextPage } from "next";
import React from 'react'
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Footer from "../components/Footer";
import brand from "../public/brand.png";

const Home: NextPage = () => {


 
  const [email, setEmail] = React.useState('');
  
  //function to post user data to the contact function
  const handleSubmit = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
    e.preventDefault();
    fetch('/api/contact', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        email: email,
      })
    })
      .then(res => res.json())
      .then(data => {
        console.log(data);
        setEmail('');
      })
      .catch(err => console.log(err));
  }



  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <div className="flex justify-between w-11/12 items-start">
          <Image src={brand} alt="brand" width={350} height={200} />
          <div className="flex flex-col space-y-8 w-2/5">
            <div className="flex flex-col space-y-2">
              <div className="flex flex-row">
              <div className="border-t-2 border-blue w-8 h-1 my-auto mx-2"></div>
              <p className="text-blue text-sm">
              Hello We Are
              </p>
              </div>
            <p className="text-green text-4xl">Coming Soon...</p>
            </div>
            <div className="flex">
              <input type="email" className="placeholder:text-blue pl-4 text-blue outline-none border-l-4 w-48 border-blue border-t border-b" placeholder="Email" />
              <button onClick={(e) => handleSubmit(e)} className="bg-blue text-white w-12 h-8 flex justify-center items-center">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M14 5l7 7m0 0l-7 7m7-7H3"
                  />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </main>
<Footer/>
    </div>
  );
};

export default Home;
