import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import brand from "../public/brand.png";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <div className="flex justify-between w-11/12">
          <Image src={brand} alt="brand" width={350} height={200} />
          <div className="flex flex-col space-y-8">
            <div className="flex flex-col space-y-2">
              <div className="flex flex-row">
              <div className="border-t-2 border-blue w-8 h-1 my-auto mx-2"></div>
              <p className="text-blue text-sm">
              Hello We Are
              </p>
              </div>
            <p className="text-green text-4xl">Coming Soon...</p>
            </div>
            <div className="flex border-l-4 border-blue border-t border-b">
              <input type="email" className="placeholder:text-blue pl-4 text-blue outline-none" placeholder="Email" />
              <button className="bg-blue text-white w-12 h-8 flex justify-center items-center">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M14 5l7 7m0 0l-7 7m7-7H3"
                  />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
